[build]
  command = "npm run build:ssg"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api"

# SPA fallback: Route all unmatched requests to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
